## Part 1: Preprocessing

In [1]:
# Import our dependencies
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from tensorflow.keras.models import Model
from tensorflow.keras import layers

from encoding_functions import label_encode_columns, label_encode_test_df, ohe_columns, ohe_columns_test


#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [2]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [3]:
attrition_df['JobLevel'].unique()

array([2, 1, 3, 4, 5])

In [4]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[['Attrition', 'Department']]
print(y_df['Attrition'].unique())
print(y_df['Department'].unique())
dept_predictions_count = len(y_df['Department'].unique())
att_predictions_count = len(y_df['Attrition'].unique())
print(dept_predictions_count)
print(att_predictions_count)
y_df.head(2)

['Yes' 'No']
['Sales' 'Research & Development' 'Human Resources']
3
2


Attrition              Department
0       Yes                   Sales
1        No  Research & Development

In [5]:
# Create a list of at least 10 column names to use as X data
x_columns = ['Age', 'Education', 'EducationField', 'HourlyRate', 'JobLevel',
        'MaritalStatus', 'JobRole', 'NumCompaniesWorked', 'PerformanceRating', 'TotalWorkingYears',
        'TrainingTimesLastYear', 'YearsAtCompany', 'YearsInCurrentRole']

# Create X_df using your selected columns
X_df = attrition_df[x_columns]

# Show the data types for X_df
X_df.dtypes


Age                       int64
Education                 int64
EducationField           object
HourlyRate                int64
JobLevel                  int64
MaritalStatus            object
JobRole                  object
NumCompaniesWorked        int64
PerformanceRating         int64
TotalWorkingYears         int64
TrainingTimesLastYear     int64
YearsAtCompany            int64
YearsInCurrentRole        int64
dtype: object

In [6]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_df, y_df)


In [7]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary
# EducationField MaritalStatus JobRole
print(X_df['EducationField'].unique())
print(X_df['MaritalStatus'].unique())
print(X_df['JobRole'].unique())

['Life Sciences' 'Other' 'Medical' 'Marketing' 'Technical Degree'
 'Human Resources']
['Single' 'Married' 'Divorced']
['Sales Executive' 'Research Scientist' 'Laboratory Technician'
 'Manufacturing Director' 'Healthcare Representative' 'Manager'
 'Sales Representative' 'Research Director' 'Human Resources']


In [8]:
X_test.head()

Age  Education    EducationField  HourlyRate  JobLevel MaritalStatus  \
1266   41          4     Life Sciences          94         1      Divorced   
1405   31          3           Medical          40         3       Married   
1209   60          4           Medical          92         3      Divorced   
1340   36          4  Technical Degree          63         2       Married   
407    45          2     Life Sciences          69         1       Married   

                        JobRole  NumCompaniesWorked  PerformanceRating  \
1266      Laboratory Technician                   1                  4   
1405          Research Director                   4                  4   
1209  Healthcare Representative                   3                  4   
1340            Sales Executive                   1                  3   
407          Research Scientist                   3                  4   

      TotalWorkingYears  TrainingTimesLastYear  YearsAtCompany  \
1266                  5                      2               5   
1405                 13                      2              11   
1209                 19                      2               1   
1340                 10                      4              10   
407                   8                      3               2   

      YearsInCurrentRole  
1266                   3  
1405                   7  
1209                   0  
1340                   9  
407                    2

In [9]:
columns_to_encode = ['EducationField', 'MaritalStatus', 'JobRole']

In [10]:
X_train_encoded, label_encoders = label_encode_columns(columns_to_encode, X_train.copy())

print(X_train_encoded.dtypes)
X_train_encoded.head()


Age                      int64
Education                int64
EducationField           int64
HourlyRate               int64
JobLevel                 int64
MaritalStatus            int64
JobRole                  int64
NumCompaniesWorked       int64
PerformanceRating        int64
TotalWorkingYears        int64
TrainingTimesLastYear    int64
YearsAtCompany           int64
YearsInCurrentRole       int64
dtype: object


Age  Education  EducationField  HourlyRate  JobLevel  MaritalStatus  \
833   27          3               1          55         1              1   
447   35          3               2          85         2              1   
3     33          4               1          56         1              1   
398   37          5               3          72         2              1   
102   20          3               1          66         1              2   

     JobRole  NumCompaniesWorked  PerformanceRating  TotalWorkingYears  \
833        6                   1                  3                  4   
447        7                   9                  3                 15   
3          6                   1                  3                  8   
398        6                   3                  3                 15   
102        2                   1                  3                  1   

     TrainingTimesLastYear  YearsAtCompany  YearsInCurrentRole  
833                      0               4                   2  
447                      2              11                   9  
3                        3               8                   7  
398                      2              13                  11  
102                      5               1                   0

In [11]:
X_test_encoded = label_encode_test_df(label_encoders, X_test.copy())
X_test_encoded.head()

Age  Education  EducationField  HourlyRate  JobLevel  MaritalStatus  \
1266   41          4               1          94         1              0   
1405   31          3               3          40         3              1   
1209   60          4               3          92         3              0   
1340   36          4               5          63         2              1   
407    45          2               1          69         1              1   

      JobRole  NumCompaniesWorked  PerformanceRating  TotalWorkingYears  \
1266        2                   1                  4                  5   
1405        5                   4                  4                 13   
1209        0                   3                  4                 19   
1340        7                   1                  3                 10   
407         6                   3                  4                  8   

      TrainingTimesLastYear  YearsAtCompany  YearsInCurrentRole  
1266                      2               5                   3  
1405                      2              11                   7  
1209                      2               1                   0  
1340                      4              10                   9  
407                       3               2                   2

In [12]:
# Create a StandardScaler
label_scaler = StandardScaler()

# Fit the StandardScaler to the training data
label_scaler.fit(X_train_encoded)

# Scale the training and testing data
X_train_encoded_scaled = label_scaler.transform(X_train_encoded)
X_test_encoded_scaled = label_scaler.transform(X_test_encoded)


In [13]:
# Create a OneHotEncoder for the Department column
# Fit the encoder to the training data
# Create two new variables by applying the encoder
# to the training and testing data

# Create a OneHotEncoder for the Attrition column

# Fit the encoder to the training data

# Create two new variables by applying the encoder
# to the training and testing data


y_colums_to_encode = ['Department', 'Attrition']
y_train, y_ohe_encoders  = ohe_columns(y_colums_to_encode, y_train.copy())
y_test = ohe_columns_test(y_ohe_encoders, y_test.copy())

In [14]:
y_department_values = y_train.filter(regex='Department').values
y_department_test_values = y_test.filter(regex='Department').values
print(y_department_values)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 ...
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]]


In [15]:
y_attrition_values = y_train.filter(regex='Attrition').values
y_attrition_test_values = y_test.filter(regex='Attrition').values
print(y_attrition_values)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]


## Create, Compile, and Train the Model

In [16]:
# Find the number of columns in the X training data
num_columns = X_train.shape[1]

# Create the input layer
input_layer = layers.Input(shape=(num_columns,), name='input_features')

# Create at least two shared layers
shared_layer_one = layers.Dense(64, activation='relu')(input_layer)
shared_layer_two = layers.Dense(128, activation='relu')(shared_layer_one)


In [17]:
# Create a branch for Department
# with a hidden layer and an output layer
# Create the hidden layer
dept_layer_one = layers.Dense(64, activation='relu')(shared_layer_two)

# Create the output layer
dept_output = layers.Dense(dept_predictions_count, activation='softmax', name='dept_output')(dept_layer_one)

In [18]:
# Create a branch for Attrition
# with a hidden layer and an output layer
# Create the hidden layer
att_layer_one = layers.Dense(64, activation='relu')(shared_layer_two)

# Create the output layer
att_output = layers.Dense(att_predictions_count, activation='sigmoid', name='att_output')(att_layer_one)

In [19]:
# Create the model
model = Model(inputs=input_layer, outputs=[dept_output, att_output])

# Compile the model
model.compile(optimizer='adam',
              loss={'dept_output': 'categorical_crossentropy',
                    'att_output': 'binary_crossentropy'},
                metrics={'dept_output': 'accuracy', 'att_output':'accuracy'})

# Summarize the model
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input_features            │ (None, 13)             │              0 │ -                      │
│ (InputLayer)              │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense (Dense)             │ (None, 64)             │            896 │ input_features[0][0]   │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_1 (Dense)           │ (None, 128)            │          8,320 │ dense[0][0]            │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_2 (Dense)           │ (None, 64)             │          8,256 │ dense_1[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_3 (Dense)           │ (None, 64)             │          8,256 │ dense_1[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dept_output (Dense)       │ (None, 3)              │            195 │ dense_2[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ att_output (Dense)        │ (None, 2)              │            130 │ dense_3[0][0]          │
└───────────────────────────┴────────────────────────┴────────────────┴────────────────────────┘

 Total params: 26,053 (101.77 KB)

 Trainable params: 26,053 (101.77 KB)

 Non-trainable params: 0 (0.00 B)

In [20]:
# Train the model
model.fit(
    X_train_encoded_scaled,
    {'dept_output': y_department_values, 'att_output': y_attrition_values},
    epochs=10,
    batch_size=32,
    validation_split=0.2
)

Epoch 1/10
28/28 ━━━━━━━━━━━━━━━━━━━━ 8s 13ms/step - att_output_accuracy: 0.7984 - dept_output_accuracy: 0.5323 - loss: 1.4728 - val_att_output_accuracy: 0.8959 - val_dept_output_accuracy: 0.7557 - val_loss: 1.0985
Epoch 2/10
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - att_output_accuracy: 0.8311 - dept_output_accuracy: 0.8140 - loss: 1.0581 - val_att_output_accuracy: 0.8959 - val_dept_output_accuracy: 0.8145 - val_loss: 0.9453
Epoch 3/10
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - att_output_accuracy: 0.8336 - dept_output_accuracy: 0.8849 - loss: 0.8525 - val_att_output_accuracy: 0.8959 - val_dept_output_accuracy: 0.8597 - val_loss: 0.8252
Epoch 4/10
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - att_output_accuracy: 0.8152 - dept_output_accuracy: 0.8996 - loss: 0.7837 - val_att_output_accuracy: 0.8959 - val_dept_output_accuracy: 0.8643 - val_loss: 0.7813
Epoch 5/10
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - att_output_accuracy: 0.8246 - dept_output_accuracy: 0.9236 - loss: 0.6645 - val_att_output_

In [21]:
# Evaluate the model with the testing data
results = model.evaluate(X_test_encoded_scaled, {
    'dept_output': y_department_test_values,
    'att_output': y_attrition_test_values
    })


12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - att_output_accuracy: 0.8704 - dept_output_accuracy: 0.9127 - loss: 0.6701 


In [22]:
# Print the accuracy for both department and attrition
pred_categories = ['Department', 'Attrition']
for i, cat in enumerate(pred_categories):
    print(f"{cat} accuracy: {results[i]}")

Department accuracy: 0.6735537648200989
Attrition accuracy: 0.866847813129425


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. the accuracy may be inflated by dominant categories. Attrition maybe more No's than Yes and Department may have more of one category over the other. So that might cause issues. Precision and Recall may be better options.
2. I chose softmax for Departments - since it isn't a binary outcome, and sigmoid for Attrition since it was a binary outcome (yes/no)
3. Yes, I did a label encoder at first, but I think OneHotEncoder for the categorical data might be a way to get potential improvements.

UPDATE: After running using OneHotEncoder on X data instead of a LabelEncoder, it does seem to improve the accuracy. See below:

## BONUS USING ONE HOT ENCODER ON X DATA

In [23]:
X_train_ohe, ohe_encoders = ohe_columns(columns_to_encode, X_train.copy())
X_test_ohe = ohe_columns_test(ohe_encoders, X_test.copy())

In [24]:
# Create a StandardScaler
ohe_scaler = StandardScaler()

# Fit the StandardScaler to the training data
ohe_scaler.fit(X_train_ohe)

# Scale the training and testing data
X_train_ohe_scaled = ohe_scaler.transform(X_train_ohe)
X_test_ohe_scaled = ohe_scaler.transform(X_test_ohe)

In [25]:
# Find the number of columns in the X training data
num_columns = X_train.shape[1]

# Create the input layer
input_layer_ohe = layers.Input(shape=(num_columns,), name='input_features')

# Create at least two shared layers
shared_layer_one_ohe = layers.Dense(64, activation='relu')(input_layer_ohe)
shared_layer_two_ohe = layers.Dense(128, activation='relu')(shared_layer_one_ohe)


In [26]:
# Create a branch for Department
# with a hidden layer and an output layer
# Create the hidden layer
dept_layer_one_ohe = layers.Dense(64, activation='relu')(shared_layer_two_ohe)

# Create the output layer
dept_output_ohe = layers.Dense(dept_predictions_count, activation='softmax', name='dept_output')(dept_layer_one_ohe)

In [27]:
# Create a branch for Attrition
# with a hidden layer and an output layer
# Create the hidden layer
att_layer_one_ohe = layers.Dense(64, activation='relu')(shared_layer_two_ohe)

# Create the output layer
att_output_ohe = layers.Dense(att_predictions_count, activation='sigmoid', name='att_output')(att_layer_one_ohe)

In [28]:
# Create the model
model_ohe = Model(inputs=input_layer, outputs=[dept_output, att_output])

# Compile the model
model_ohe.compile(optimizer='adam',
              loss={'dept_output': 'categorical_crossentropy',
                    'att_output': 'binary_crossentropy'},
                metrics={'dept_output': 'accuracy', 'att_output':'accuracy'})

# Summarize the model
model_ohe.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input_features            │ (None, 13)             │              0 │ -                      │
│ (InputLayer)              │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense (Dense)             │ (None, 64)             │            896 │ input_features[0][0]   │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_1 (Dense)           │ (None, 128)            │          8,320 │ dense[0][0]            │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_2 (Dense)           │ (None, 64)             │          8,256 │ dense_1[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_3 (Dense)           │ (None, 64)             │          8,256 │ dense_1[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dept_output (Dense)       │ (None, 3)              │            195 │ dense_2[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ att_output (Dense)        │ (None, 2)              │            130 │ dense_3[0][0]          │
└───────────────────────────┴────────────────────────┴────────────────┴────────────────────────┘

 Total params: 26,053 (101.77 KB)

 Trainable params: 26,053 (101.77 KB)

 Non-trainable params: 0 (0.00 B)

In [29]:
# Train the model
model_ohe.fit(
    X_train_encoded_scaled,
    {'dept_output': y_department_values, 'att_output': y_attrition_values},
    epochs=10,
    batch_size=32,
    validation_split=0.2
)

Epoch 1/10
28/28 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - att_output_accuracy: 0.8445 - dept_output_accuracy: 0.9459 - loss: 0.5361 - val_att_output_accuracy: 0.8733 - val_dept_output_accuracy: 0.8643 - val_loss: 0.6836
Epoch 2/10
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - att_output_accuracy: 0.8487 - dept_output_accuracy: 0.9430 - loss: 0.5102 - val_att_output_accuracy: 0.8778 - val_dept_output_accuracy: 0.8733 - val_loss: 0.6878
Epoch 3/10
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - att_output_accuracy: 0.8411 - dept_output_accuracy: 0.9337 - loss: 0.5162 - val_att_output_accuracy: 0.8597 - val_dept_output_accuracy: 0.8733 - val_loss: 0.7487
Epoch 4/10
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - att_output_accuracy: 0.8536 - dept_output_accuracy: 0.9422 - loss: 0.4994 - val_att_output_accuracy: 0.8462 - val_dept_output_accuracy: 0.8733 - val_loss: 0.7632
Epoch 5/10
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - att_output_accuracy: 0.8558 - dept_output_accuracy: 0.9420 - loss: 0.4774 - val_att_output_

In [30]:
# Evaluate the model with the testing data
results_ohe = model_ohe.evaluate(X_test_encoded_scaled, {
    'dept_output': y_department_test_values,
    'att_output': y_attrition_test_values
    })


12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - att_output_accuracy: 0.8469 - dept_output_accuracy: 0.8980 - loss: 0.7454 


In [31]:
# Print the accuracy for both department and attrition
pred_categories = ['Department', 'Attrition']
for i, cat in enumerate(pred_categories):
    print(f"{cat} accuracy: {results_ohe[i]}")

Department accuracy: 0.7428005933761597
Attrition accuracy: 0.83423912525177
