## Part 1: Preprocessing

In [65]:
# Import our dependencies
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from tensorflow.keras.models import Model
from tensorflow.keras import layers

from encoding_functions import label_encode_columns, label_encode_test_df, ohe_columns, ohe_columns_test


#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [66]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [67]:
attrition_df['JobLevel'].unique()

array([2, 1, 3, 4, 5])

In [68]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[['Attrition', 'Department']]
print(y_df['Attrition'].unique())
print(y_df['Department'].unique())
dept_predictions_count = len(y_df['Department'].unique())
att_predictions_count = len(y_df['Attrition'].unique())
print(dept_predictions_count)
print(att_predictions_count)
y_df.head(2)

['Yes' 'No']
['Sales' 'Research & Development' 'Human Resources']
3
2


Attrition              Department
0       Yes                   Sales
1        No  Research & Development

In [69]:
# Create a list of at least 10 column names to use as X data
x_columns = ['Age', 'Education', 'EducationField', 'HourlyRate', 'JobLevel',
        'MaritalStatus', 'JobRole', 'NumCompaniesWorked', 'PerformanceRating', 'TotalWorkingYears',
        'TrainingTimesLastYear', 'YearsAtCompany', 'YearsInCurrentRole']

# Create X_df using your selected columns
X_df = attrition_df[x_columns]

# Show the data types for X_df
X_df.dtypes


Age                       int64
Education                 int64
EducationField           object
HourlyRate                int64
JobLevel                  int64
MaritalStatus            object
JobRole                  object
NumCompaniesWorked        int64
PerformanceRating         int64
TotalWorkingYears         int64
TrainingTimesLastYear     int64
YearsAtCompany            int64
YearsInCurrentRole        int64
dtype: object

In [72]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_df, y_df)


In [73]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary
# EducationField MaritalStatus JobRole
print(X_df['EducationField'].unique())
print(X_df['MaritalStatus'].unique())
print(X_df['JobRole'].unique())

['Life Sciences' 'Other' 'Medical' 'Marketing' 'Technical Degree'
 'Human Resources']
['Single' 'Married' 'Divorced']
['Sales Executive' 'Research Scientist' 'Laboratory Technician'
 'Manufacturing Director' 'Healthcare Representative' 'Manager'
 'Sales Representative' 'Research Director' 'Human Resources']


In [74]:
X_test.head()

Age  Education    EducationField  HourlyRate  JobLevel MaritalStatus  \
1423   22          2     Life Sciences          63         1        Single   
900    36          3  Technical Degree          46         1       Married   
564    45          2  Technical Degree          46         2        Single   
467    37          4           Medical          69         3      Divorced   
973    35          3           Medical          60         2       Married   

                    JobRole  NumCompaniesWorked  PerformanceRating  \
1423     Research Scientist                   0                  3   
900      Research Scientist                   1                  3   
564    Sales Representative                   0                  3   
467         Sales Executive                   1                  3   
973   Laboratory Technician                   0                  3   

      TotalWorkingYears  TrainingTimesLastYear  YearsAtCompany  \
1423                  4                      2               3   
900                  12                      2              11   
564                   9                      3               8   
467                   9                      6               9   
973                  10                      0               9   

      YearsInCurrentRole  
1423                   2  
900                   10  
564                    7  
467                    5  
973                    7

In [75]:
columns_to_encode = ['EducationField', 'MaritalStatus', 'JobRole']

In [76]:
X_train_encoded, label_encoders = label_encode_columns(columns_to_encode, X_train.copy())

print(X_train_encoded.dtypes)
X_train_encoded.head()


Age                      int64
Education                int64
EducationField           int64
HourlyRate               int64
JobLevel                 int64
MaritalStatus            int64
JobRole                  int64
NumCompaniesWorked       int64
PerformanceRating        int64
TotalWorkingYears        int64
TrainingTimesLastYear    int64
YearsAtCompany           int64
YearsInCurrentRole       int64
dtype: object


Age  Education  EducationField  HourlyRate  JobLevel  MaritalStatus  \
172    36          2               3          30         1              2   
1042   44          3               1          90         1              2   
1002   35          2               1          60         3              2   
1297   26          2               3          69         1              1   
965    25          1               3          67         1              1   

      JobRole  NumCompaniesWorked  PerformanceRating  TotalWorkingYears  \
172         2                   4                  3                 13   
1042        2                   3                  3                  7   
1002        4                   2                  3                 10   
1297        1                   0                  3                  6   
965         2                   3                  3                  7   

      TrainingTimesLastYear  YearsAtCompany  YearsInCurrentRole  
172                       3               8                   7  
1042                      5               5                   2  
1002                      2               2                   2  
1297                      3               5                   1  
965                       6               3                   2

In [77]:
X_test_encoded = label_encode_test_df(label_encoders, X_test.copy())
X_test_encoded.head()

Age  Education  EducationField  HourlyRate  JobLevel  MaritalStatus  \
1423   22          2               1          63         1              2   
900    36          3               5          46         1              1   
564    45          2               5          46         2              2   
467    37          4               3          69         3              0   
973    35          3               3          60         2              1   

      JobRole  NumCompaniesWorked  PerformanceRating  TotalWorkingYears  \
1423        6                   0                  3                  4   
900         6                   1                  3                 12   
564         8                   0                  3                  9   
467         7                   1                  3                  9   
973         2                   0                  3                 10   

      TrainingTimesLastYear  YearsAtCompany  YearsInCurrentRole  
1423                      2               3                   2  
900                       2              11                  10  
564                       3               8                   7  
467                       6               9                   5  
973                       0               9                   7

In [78]:
X_train_hot_encode, ohe_encoders = ohe_columns(columns_to_encode, X_train.copy())
X_train_hot_encode.head()

Age  Education  HourlyRate  JobLevel  NumCompaniesWorked  \
0   36          2          30         1                   4   
1   44          3          90         1                   3   
2   35          2          60         3                   2   
3   26          2          69         1                   0   
4   25          1          67         1                   3   

   PerformanceRating  TotalWorkingYears  TrainingTimesLastYear  \
0                  3                 13                      3   
1                  3                  7                      5   
2                  3                 10                      2   
3                  3                  6                      3   
4                  3                  7                      6   

   YearsAtCompany  YearsInCurrentRole  ...  MaritalStatus_Single  \
0               8                   7  ...                   1.0   
1               5                   2  ...                   1.0   
2               2                   2  ...                   1.0   
3               5                   1  ...                   0.0   
4               3                   2  ...                   0.0   

   JobRole_Healthcare Representative  JobRole_Human Resources  \
0                                0.0                      0.0   
1                                0.0                      0.0   
2                                0.0                      0.0   
3                                0.0                      1.0   
4                                0.0                      0.0   

   JobRole_Laboratory Technician  JobRole_Manager  \
0                            1.0              0.0   
1                            1.0              0.0   
2                            0.0              0.0   
3                            0.0              0.0   
4                            1.0              0.0   

   JobRole_Manufacturing Director  JobRole_Research Director  \
0                             0.0                        0.0   
1                             0.0                        0.0   
2                             1.0                        0.0   
3                             0.0                        0.0   
4                             0.0                        0.0   

   JobRole_Research Scientist  JobRole_Sales Executive  \
0                         0.0                      0.0   
1                         0.0                      0.0   
2                         0.0                      0.0   
3                         0.0                      0.0   
4                         0.0                      0.0   

   JobRole_Sales Representative  
0                           0.0  
1                           0.0  
2                           0.0  
3                           0.0  
4                           0.0  

[5 rows x 28 columns]

In [79]:
X_test_ohe = ohe_columns_test(ohe_encoders, X_test.copy())
X_test_ohe.head()

Age  Education  HourlyRate  JobLevel  NumCompaniesWorked  \
0   22          2          63         1                   0   
1   36          3          46         1                   1   
2   45          2          46         2                   0   
3   37          4          69         3                   1   
4   35          3          60         2                   0   

   PerformanceRating  TotalWorkingYears  TrainingTimesLastYear  \
0                  3                  4                      2   
1                  3                 12                      2   
2                  3                  9                      3   
3                  3                  9                      6   
4                  3                 10                      0   

   YearsAtCompany  YearsInCurrentRole  ...  MaritalStatus_Single  \
0               3                   2  ...                   1.0   
1              11                  10  ...                   0.0   
2               8                   7  ...                   1.0   
3               9                   5  ...                   0.0   
4               9                   7  ...                   0.0   

   JobRole_Healthcare Representative  JobRole_Human Resources  \
0                                0.0                      0.0   
1                                0.0                      0.0   
2                                0.0                      0.0   
3                                0.0                      0.0   
4                                0.0                      0.0   

   JobRole_Laboratory Technician  JobRole_Manager  \
0                            0.0              0.0   
1                            0.0              0.0   
2                            0.0              0.0   
3                            0.0              0.0   
4                            1.0              0.0   

   JobRole_Manufacturing Director  JobRole_Research Director  \
0                             0.0                        0.0   
1                             0.0                        0.0   
2                             0.0                        0.0   
3                             0.0                        0.0   
4                             0.0                        0.0   

   JobRole_Research Scientist  JobRole_Sales Executive  \
0                         1.0                      0.0   
1                         1.0                      0.0   
2                         0.0                      0.0   
3                         0.0                      1.0   
4                         0.0                      0.0   

   JobRole_Sales Representative  
0                           0.0  
1                           0.0  
2                           1.0  
3                           0.0  
4                           0.0  

[5 rows x 28 columns]

In [80]:
# Create a StandardScaler
label_scaler = StandardScaler()

# Fit the StandardScaler to the training data
label_scaler.fit(X_train_encoded)

# Scale the training and testing data
X_train_encoded_scaled = label_scaler.transform(X_train_encoded)
X_test_encoded_scaled = label_scaler.transform(X_test_encoded)


In [81]:
# Create a OneHotEncoder for the Department column
# Fit the encoder to the training data
# Create two new variables by applying the encoder
# to the training and testing data

# Create a OneHotEncoder for the Attrition column

# Fit the encoder to the training data

# Create two new variables by applying the encoder
# to the training and testing data


y_colums_to_encode = ['Department', 'Attrition']
y_train, y_ohe_encoders  = ohe_columns(y_colums_to_encode, y_train.copy())
y_test = ohe_columns_test(y_ohe_encoders, y_test.copy())

In [82]:
y_department_values = y_train.filter(regex='Department').values
y_department_test_values = y_test.filter(regex='Department').values
print(y_department_values)

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 ...
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


In [83]:
y_attrition_values = y_train.filter(regex='Attrition').values
y_attrition_test_values = y_test.filter(regex='Attrition').values
print(y_attrition_values)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]


## Create, Compile, and Train the Model

In [84]:
# Find the number of columns in the X training data
num_columns = X_train.shape[1]

# Create the input layer
input_layer = layers.Input(shape=(num_columns,), name='input_features')

# Create at least two shared layers
shared_layer_one = layers.Dense(64, activation='relu')(input_layer)
shared_layer_two = layers.Dense(128, activation='relu')(shared_layer_one)


In [85]:
# Create a branch for Department
# with a hidden layer and an output layer
# Create the hidden layer
dept_layer_one = layers.Dense(64, activation='relu')(shared_layer_two)

# Create the output layer
dept_output = layers.Dense(dept_predictions_count, activation='softmax', name='dept_output')(dept_layer_one)

In [86]:
# Create a branch for Attrition
# with a hidden layer and an output layer
# Create the hidden layer
att_layer_one = layers.Dense(64, activation='relu')(shared_layer_two)

# Create the output layer
att_output = layers.Dense(att_predictions_count, activation='sigmoid', name='att_output')(att_layer_one)

In [87]:
# Create the model
model = Model(inputs=input_layer, outputs=[dept_output, att_output])

# Compile the model
model.compile(optimizer='adam',
              loss={'dept_output': 'categorical_crossentropy',
                    'att_output': 'binary_crossentropy'},
                metrics={'dept_output': 'accuracy', 'att_output':'accuracy'})

# Summarize the model
model.summary()

Model: "functional_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input_features            │ (None, 13)             │              0 │ -                      │
│ (InputLayer)              │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_12 (Dense)          │ (None, 64)             │            896 │ input_features[0][0]   │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_13 (Dense)          │ (None, 128)            │          8,320 │ dense_12[0][0]         │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_14 (Dense)          │ (None, 64)             │          8,256 │ dense_13[0][0]         │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_15 (Dense)          │ (None, 64)             │          8,256 │ dense_13[0][0]         │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dept_output (Dense)       │ (None, 3)              │            195 │ dense_14[0][0]         │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ att_output (Dense)        │ (None, 2)              │            130 │ dense_15[0][0]         │
└───────────────────────────┴────────────────────────┴────────────────┴────────────────────────┘

 Total params: 26,053 (101.77 KB)

 Trainable params: 26,053 (101.77 KB)

 Non-trainable params: 0 (0.00 B)

In [88]:
# Train the model
model.fit(
    X_train_encoded_scaled,
    {'dept_output': y_department_values, 'att_output': y_attrition_values},
    epochs=10,
    batch_size=32,
    validation_split=0.2
)

Epoch 1/10
28/28 ━━━━━━━━━━━━━━━━━━━━ 4s 25ms/step - att_output_accuracy: 0.8461 - dept_output_accuracy: 0.5196 - loss: 1.4821 - val_att_output_accuracy: 0.8009 - val_dept_output_accuracy: 0.7602 - val_loss: 1.2290
Epoch 2/10
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - att_output_accuracy: 0.8386 - dept_output_accuracy: 0.7814 - loss: 1.0559 - val_att_output_accuracy: 0.8009 - val_dept_output_accuracy: 0.8462 - val_loss: 1.0486
Epoch 3/10
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - att_output_accuracy: 0.8359 - dept_output_accuracy: 0.8475 - loss: 0.8779 - val_att_output_accuracy: 0.8009 - val_dept_output_accuracy: 0.8688 - val_loss: 0.9236
Epoch 4/10
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - att_output_accuracy: 0.8340 - dept_output_accuracy: 0.9166 - loss: 0.7534 - val_att_output_accuracy: 0.8009 - val_dept_output_accuracy: 0.8643 - val_loss: 0.8706
Epoch 5/10
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - att_output_accuracy: 0.8495 - dept_output_accuracy: 0.9125 - loss: 0.6641 - val_att_output

In [89]:
# Evaluate the model with the testing data
results = model.evaluate(X_test_encoded_scaled, {
    'dept_output': y_department_test_values,
    'att_output': y_attrition_test_values
    })


12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - att_output_accuracy: 0.8736 - dept_output_accuracy: 0.9071 - loss: 0.6589


In [90]:
# Print the accuracy for both department and attrition
pred_categories = ['Department', 'Attrition']
for i, cat in enumerate(pred_categories):
    print(f"{cat} accuracy: {results[i]}")

Department accuracy: 0.7393943071365356
Attrition accuracy: 0.845108687877655


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. the accuracy may be inflated by dominant categories. Attrition maybe more No's than Yes and Department may have more of one category over the other. So that might cause issues. Precision and Recall may be better options.
2. I chose softmax for Departments - since it isn't a binary outcome, and sigmoid for Attrition since it was a binary outcome (yes/no)
3. Yes, I did a label encoder at first, but I think OneHotEncoder for the categorical data might be a way to get potential improvements.