## Part 1: Preprocessing

In [63]:
# Import our dependencies
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from tensorflow.keras.models import Model
from tensorflow.keras import layers

from encoding_functions import label_encode_columns, label_encode_test_df, ohe_columns, ohe_columns_test


#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [64]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [65]:
attrition_df['JobLevel'].unique()

array([2, 1, 3, 4, 5], dtype=int64)

In [66]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[['Attrition', 'Department']]
print(y_df['Attrition'].unique())
print(y_df['Department'].unique())
dept_predictions_count = len(y_df['Department'].unique())
att_predictions_count = len(y_df['Attrition'].unique())
print(dept_predictions_count)
print(att_predictions_count)
y_df.head(2)

['Yes' 'No']
['Sales' 'Research & Development' 'Human Resources']
3
2


Attrition              Department
0       Yes                   Sales
1        No  Research & Development

In [67]:
# Create a list of at least 10 column names to use as X data
x_columns = ['Age', 'Education', 'EducationField', 'HourlyRate', 'JobLevel',
        'MaritalStatus', 'JobRole', 'NumCompaniesWorked', 'PerformanceRating', 'TotalWorkingYears',
        'TrainingTimesLastYear', 'YearsAtCompany', 'YearsInCurrentRole']

# Create X_df using your selected columns
X_df = attrition_df[x_columns]

# Show the data types for X_df
X_df.dtypes


Age                       int64
Education                 int64
EducationField           object
HourlyRate                int64
JobLevel                  int64
MaritalStatus            object
JobRole                  object
NumCompaniesWorked        int64
PerformanceRating         int64
TotalWorkingYears         int64
TrainingTimesLastYear     int64
YearsAtCompany            int64
YearsInCurrentRole        int64
dtype: object

In [68]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_df, y_df)


In [69]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary
# EducationField MaritalStatus JobRole
print(X_df['EducationField'].unique())
print(X_df['MaritalStatus'].unique())
print(X_df['JobRole'].unique())

['Life Sciences' 'Other' 'Medical' 'Marketing' 'Technical Degree'
 'Human Resources']
['Single' 'Married' 'Divorced']
['Sales Executive' 'Research Scientist' 'Laboratory Technician'
 'Manufacturing Director' 'Healthcare Representative' 'Manager'
 'Sales Representative' 'Research Director' 'Human Resources']


In [70]:
X_test.head()

Age  Education EducationField  HourlyRate  JobLevel MaritalStatus  \
819    28          1  Life Sciences          67         1       Married   
1012   31          4  Life Sciences          50         1        Single   
481    34          2  Life Sciences          83         1       Married   
943    46          2  Life Sciences          44         1        Single   
881    32          2  Life Sciences          38         2        Single   

                   JobRole  NumCompaniesWorked  PerformanceRating  \
819     Research Scientist                   0                  3   
1012  Sales Representative                   1                  3   
481     Research Scientist                   1                  3   
943        Human Resources                   6                  3   
881     Research Scientist                   4                  3   

      TotalWorkingYears  TrainingTimesLastYear  YearsAtCompany  \
819                   6                      2               5   
1012                  1                      3               1   
481                   6                      3               6   
943                  10                      3               7   
881                  10                      2               8   

      YearsInCurrentRole  
819                    3  
1012                   0  
481                    5  
943                    6  
881                    7

In [71]:
columns_to_encode = ['EducationField', 'MaritalStatus', 'JobRole']

In [72]:
X_train_encoded, label_encoders = label_encode_columns(columns_to_encode, X_train.copy())

print(X_train_encoded.dtypes)
X_train_encoded.head()


Age                      int64
Education                int64
EducationField           int32
HourlyRate               int64
JobLevel                 int64
MaritalStatus            int32
JobRole                  int32
NumCompaniesWorked       int64
PerformanceRating        int64
TotalWorkingYears        int64
TrainingTimesLastYear    int64
YearsAtCompany           int64
YearsInCurrentRole       int64
dtype: object


Age  Education  EducationField  HourlyRate  JobLevel  MaritalStatus  \
561   52          4               2          31         4              1   
516   23          3               3          58         1              1   
173   30          3               3          66         2              0   
982   38          3               1          57         1              0   
398   37          5               3          72         2              1   

     JobRole  NumCompaniesWorked  PerformanceRating  TotalWorkingYears  \
561        3                   1                  3                 34   
516        6                   2                  3                  5   
173        2                   1                  3                 12   
982        6                   1                  3                  4   
398        6                   3                  3                 15   

     TrainingTimesLastYear  YearsAtCompany  YearsInCurrentRole  
561                      3              34                   6  
516                      3               3                   2  
173                      4              12                   9  
982                      2               4                   2  
398                      2              13                  11

In [73]:
X_test_encoded = label_encode_test_df(label_encoders, X_test.copy())
X_test_encoded.head()

Age  Education  EducationField  HourlyRate  JobLevel  MaritalStatus  \
819    28          1               1          67         1              1   
1012   31          4               1          50         1              2   
481    34          2               1          83         1              1   
943    46          2               1          44         1              2   
881    32          2               1          38         2              2   

      JobRole  NumCompaniesWorked  PerformanceRating  TotalWorkingYears  \
819         6                   0                  3                  6   
1012        8                   1                  3                  1   
481         6                   1                  3                  6   
943         1                   6                  3                 10   
881         6                   4                  3                 10   

      TrainingTimesLastYear  YearsAtCompany  YearsInCurrentRole  
819                       2               5                   3  
1012                      3               1                   0  
481                       3               6                   5  
943                       3               7                   6  
881                       2               8                   7

In [74]:
X_train_hot_encode, ohe_encoders = ohe_columns(columns_to_encode, X_train.copy())
X_train_hot_encode.head()

Age  Education  HourlyRate  JobLevel  NumCompaniesWorked  \
0   52          4          31         4                   1   
1   23          3          58         1                   2   
2   30          3          66         2                   1   
3   38          3          57         1                   1   
4   37          5          72         2                   3   

   PerformanceRating  TotalWorkingYears  TrainingTimesLastYear  \
0                  3                 34                      3   
1                  3                  5                      3   
2                  3                 12                      4   
3                  3                  4                      2   
4                  3                 15                      2   

   YearsAtCompany  YearsInCurrentRole  ...  MaritalStatus_Single  \
0              34                   6  ...                   0.0   
1               3                   2  ...                   0.0   
2              12                   9  ...                   0.0   
3               4                   2  ...                   0.0   
4              13                  11  ...                   0.0   

   JobRole_Healthcare Representative  JobRole_Human Resources  \
0                                0.0                      0.0   
1                                0.0                      0.0   
2                                0.0                      0.0   
3                                0.0                      0.0   
4                                0.0                      0.0   

   JobRole_Laboratory Technician  JobRole_Manager  \
0                            0.0              1.0   
1                            0.0              0.0   
2                            1.0              0.0   
3                            0.0              0.0   
4                            0.0              0.0   

   JobRole_Manufacturing Director  JobRole_Research Director  \
0                             0.0                        0.0   
1                             0.0                        0.0   
2                             0.0                        0.0   
3                             0.0                        0.0   
4                             0.0                        0.0   

   JobRole_Research Scientist  JobRole_Sales Executive  \
0                         0.0                      0.0   
1                         1.0                      0.0   
2                         0.0                      0.0   
3                         1.0                      0.0   
4                         1.0                      0.0   

   JobRole_Sales Representative  
0                           0.0  
1                           0.0  
2                           0.0  
3                           0.0  
4                           0.0  

[5 rows x 28 columns]

In [75]:
X_test_ohe = ohe_columns_test(ohe_encoders, X_test.copy())
X_test_ohe.head()

Age  Education  HourlyRate  JobLevel  NumCompaniesWorked  \
0   28          1          67         1                   0   
1   31          4          50         1                   1   
2   34          2          83         1                   1   
3   46          2          44         1                   6   
4   32          2          38         2                   4   

   PerformanceRating  TotalWorkingYears  TrainingTimesLastYear  \
0                  3                  6                      2   
1                  3                  1                      3   
2                  3                  6                      3   
3                  3                 10                      3   
4                  3                 10                      2   

   YearsAtCompany  YearsInCurrentRole  ...  MaritalStatus_Single  \
0               5                   3  ...                   0.0   
1               1                   0  ...                   1.0   
2               6                   5  ...                   0.0   
3               7                   6  ...                   1.0   
4               8                   7  ...                   1.0   

   JobRole_Healthcare Representative  JobRole_Human Resources  \
0                                0.0                      0.0   
1                                0.0                      0.0   
2                                0.0                      0.0   
3                                0.0                      1.0   
4                                0.0                      0.0   

   JobRole_Laboratory Technician  JobRole_Manager  \
0                            0.0              0.0   
1                            0.0              0.0   
2                            0.0              0.0   
3                            0.0              0.0   
4                            0.0              0.0   

   JobRole_Manufacturing Director  JobRole_Research Director  \
0                             0.0                        0.0   
1                             0.0                        0.0   
2                             0.0                        0.0   
3                             0.0                        0.0   
4                             0.0                        0.0   

   JobRole_Research Scientist  JobRole_Sales Executive  \
0                         1.0                      0.0   
1                         0.0                      0.0   
2                         1.0                      0.0   
3                         0.0                      0.0   
4                         1.0                      0.0   

   JobRole_Sales Representative  
0                           0.0  
1                           1.0  
2                           0.0  
3                           0.0  
4                           0.0  

[5 rows x 28 columns]

In [76]:
# Create a StandardScaler
label_scaler = StandardScaler()

# Fit the StandardScaler to the training data
label_scaler.fit(X_train_encoded)

# Scale the training and testing data
X_train_encoded_scaled = label_scaler.transform(X_train_encoded)
X_test_encoded_scaled = label_scaler.transform(X_test_encoded)


In [77]:
# Create a OneHotEncoder for the Department column
# Fit the encoder to the training data
# Create two new variables by applying the encoder
# to the training and testing data

# Create a OneHotEncoder for the Attrition column

# Fit the encoder to the training data

# Create two new variables by applying the encoder
# to the training and testing data


y_colums_to_encode = ['Department', 'Attrition']
y_train, y_ohe_encoders  = ohe_columns(y_colums_to_encode, y_train.copy())
y_test = ohe_columns_test(y_ohe_encoders, y_test.copy())

In [78]:
y_department_values = y_train.filter(regex='Department').values
print(y_department_values)

[[0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 ...
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


In [79]:
y_attrition_values = y_train.filter(regex='Attrition').values
print(y_attrition_values)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]


## Create, Compile, and Train the Model

In [80]:
# Find the number of columns in the X training data
num_columns = X_train.shape[1]

# Create the input layer
input_layer = layers.Input(shape=(num_columns,), name='input_features')

# Create at least two shared layers
shared_layer_one = layers.Dense(64, activation='relu')(input_layer)
shared_layer_two = layers.Dense(128, activation='relu')(shared_layer_one)

In [81]:
# Create a branch for Department
# with a hidden layer and an output layer
# Create the hidden layer
dept_layer_one = layers.Dense(64, activation='relu')(shared_layer_two)

# Create the output layer
dept_output = layers.Dense(dept_predictions_count, activation='softmax', name='dept_output')(dept_layer_one)

In [82]:
# Create a branch for Attrition
# with a hidden layer and an output layer
# Create the hidden layer
att_layer_one = layers.Dense(64, activation='relu')(shared_layer_two)

# Create the output layer
att_output = layers.Dense(att_predictions_count, activation='sigmoid', name='att_output')(att_layer_one)

In [83]:
# Create the model
model = Model(inputs=input_layer, outputs=[dept_output, att_output])

# Compile the model
model.compile(optimizer='adam',
              loss={'dept_output': 'categorical_crossentropy',
                    'att_output': 'binary_crossentropy'},
                metrics={'dept_output': 'accuracy', 'att_output':'accuracy'})

# Summarize the model
model.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_features      │ (None, 13)        │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_6 (Dense)     │ (None, 64)        │        896 │ input_features[0… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_7 (Dense)     │ (None, 128)       │      8,320 │ dense_6[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_8 (Dense)     │ (None, 64)        │      8,256 │ dense_7[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_9 (Dense)     │ (None, 64)        │      8,256 │ dense_7[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dept_output (Dense) │ (None, 3)         │        195 │ dense_8[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ att_output (Dense)  │ (None, 2)         │        130 │ dense_9[0][0]     │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 26,053 (101.77 KB)

 Trainable params: 26,053 (101.77 KB)

 Non-trainable params: 0 (0.00 B)

In [87]:
# Train the model
model.fit(
    X_train_encoded_scaled,
    {'dept_output': y_department_values, 'att_output': y_attrition_values},
    epochs=10,
    batch_size=32,
    validation_split=0.2
)

Epoch 1/10


ValueError: Arguments `target` and `output` must have the same shape. Received: target.shape=(None, 2), output.shape=(None, 3)

In [85]:
# Evaluate the model with the testing data


In [86]:
# Print the accuracy for both department and attrition


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. 
2. 
3. 